Repository footgrammer/wanna_exercise_app, pull requests merged in 2025-04, with the labels that each got.

#13 Jinju9513/issue5
  .gitignore
  lib/UI/pages/chat/chat_page.dart
Labels: feat

#14 [UI] 채팅방 리스트 구현(바텀바 제외)
  lib/UI/pages/chat/chat_room_page.dart
  lib/UI/pages/chat/widgets/chat_room_bottomsheet.dart
  lib/UI/pages/chat/widgets/chat_room_list_view.dart
  lib/UI/pages/chat/widgets/chat_room_receive.dart
  lib/UI/pages/chat/widgets/chat_room_send.dart
  lib/UI/widgets/user_profile_image.dart
  lib/main.dart
Labels: feat

#18 [UI] 채팅방 하단바 구현 및 라우터 연결
  lib/UI/pages/chat/chat_page.dart
  lib/UI/pages/chat/chat_room_page.dart
  lib/UI/pages/chat/widgets/chat_room_bottomsheet.dart
  lib/main.dart
Labels: feat

#22 [theme] theme 파일 적용
  lib/main.dart
  lib/theme/light_theme.dart
Labels: feat

#25 [UI]지도
  lib/UI/pages/map/map_page.dart
  lib/UI/pages/map/widgets/event_card_widget.dart
  lib/UI/pages/map/widgets/search_bar_widget.dart
Labels: feat

#28 [Refactor] 폴더구조 변경
  assets/images/wanna_exercise.png
  lib/data/models/chat.dart
  lib/data/models/post.dart
  lib/data/models/user.dart
  lib/data/providers/auth_provider.dart
  lib/data/providers/chat_provider.dart
  lib/data/providers/map_provider.dart
  lib/data/providers/post_provider.dart
  lib/data/providers/user_provider.dart
  lib/data/repositories/auth_repository.dart
  lib/data/repositories/chat_repository.dart
  lib/data/repositories/map_repository.dart
  lib/data/repositories/post_repository.dart
  lib/data/view_models/auth_view_model.dart
  lib/data/view_models/chat_view_model.dart
  lib/data/view_models/map_view_model.dart
  lib/data/view_models/post_view_model.dart
  lib/data/view_models/user_view_model.dart
  lib/main.dart
  lib/pages/chat/chat_page.dart
  lib/pages/chat/chat_room_page.dart
  lib/pages/chat/widgets/chat_room_bottomsheet.dart
  lib/pages/chat/widgets/chat_room_list_view.dart
  lib/pages/chat/widgets/chat_room_receive.dart
  lib/pages/chat/widgets/chat_room_send.dart
  lib/pages/home/home_page.dart
  lib/pages/login/login_page.dart
  lib/pages/login/widgets/id_text_form_field.dart
  lib/pages/login/widgets/pw_text_form_field.dart
  lib/pages/map/map_page.dart
  lib/pages/map/widgets/event_card_widget.dart
  lib/pages/map/widgets/search_bar_widget.dart
  lib/pages/post/post_page.dart
  lib/pages/profile/profile_page.dart
  lib/pages/widgets/user_profile_image.dart
  lib/themes/light_theme.dart
Labels: refactor

#31 [Data] Profile 모델 구현 및 파이어베이스 연결
  lib/main.dart
  lib/model/model/profile.dart
  lib/model/repository/profile_repository.dart
  lib/model/repository/user_repository.dart
  lib/pages/login/login_page.dart
  lib/pages/login/login_view_model.dart
  lib/pages/login/widgets/id_text_form_field.dart
  lib/pages/login/widgets/pw_text_form_field.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#33 [Logic] 로그인 로직 구현
  ios/Podfile.lock
  lib/data/models/user.dart
  lib/data/repositories/auth_repository.dart
  lib/pages/login/login_page.dart
  lib/pages/login/login_view_model.dart
  lib/pages/login/widgets/id_text_form_field.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat

#34 [Logic]지도 API 연동 및 마커구현
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  lib/main.dart
  lib/pages/map/map_page.dart
  lib/pages/map/widgets/event_card_widget.dart
  lib/pages/map/widgets/search_bar_widget.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#38 [UI]홈페이지 구현하기
  lib/pages/home/home_page.dart
  lib/pages/home/widgets/build_activity_button.dart
  lib/pages/home/widgets/custom_bottom_nav_bar.dart
  lib/pages/home/widgets/home_content_page.dart
Labels: feat

#54 [Logic] 회원가입 기능 구현
  lib/core/on_submitted_func.dart
  lib/data/repositories/auth_repository.dart
  lib/data/view_models/auth_view_model.dart
  lib/main.dart
  lib/pages/login/login_page.dart
  lib/pages/register/register_page.dart
  pubspec.lock
Labels: feat

#58 Jinju9513/issue51
  lib/data/repositories/map_repository.dart
  lib/data/view_models/map_view_model.dart
  lib/pages/map/map_page.dart
  lib/pages/map/widgets/event_card_widget.dart
  lib/pages/map/widgets/search_bar_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#61 [UI] 홈페이지 ui 수정
  lib/pages/home/widgets/build_activity_button.dart
  lib/pages/home/widgets/home_content_page.dart
  pubspec.lock
Labels: feat

#64 [Logic]지도 현재위치 반경띄우기
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/pages/map/map_page.dart
  lib/pages/map/widgets/search_bar_widget.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat

#67 [Logic] 로그인, 회원가입 페이지 유효성 검사, 전화번호 중복확인
  lib/core/validator_login.dart
  lib/core/validator_util.dart
  lib/data/repositories/auth_repository.dart
  lib/data/view_models/auth_view_model.dart
  lib/data/view_models/login_user_view_model.dart
  lib/main.dart
  lib/pages/login/login_page.dart
  lib/pages/register/register_page.dart
  lib/pages/widgets/nickname_text_form_field.dart
  lib/pages/widgets/phone_text_form_field.dart
  lib/pages/widgets/pw_check_text_form_field.dart
  lib/pages/widgets/pw_text_form_field.dart
  lib/pages/widgets/show_confirm_pop_up.dart
  lib/pages/widgets/show_custom_snack_bar.dart
Labels: feat

#74 [Board] 게시판 목록 및 상세 페이지 UI 완성
  lib/data/models/board.dart
  lib/data/providers/board_provider.dart
  lib/data/providers/post_provider.dart
  lib/data/repositories/board_repository.dart
  lib/data/repositories/post_repository.dart
  lib/data/repositories/profile_repository.dart
  lib/data/view_models/board_view_model.dart
  lib/data/view_models/post_view_model.dart
  lib/pages/board/board_detail_page.dart
  lib/pages/board/board_page.dart
  lib/pages/board/widgets/board_item.dart
  lib/pages/board/widgets/filter_button.dart
  lib/pages/chat/chat_page.dart
  lib/pages/chat/widgets/chat_room_receive.dart
  lib/pages/home/home_page.dart
  lib/pages/home/widgets/custom_bottom_nav_bar.dart
  lib/pages/login/login_page.dart
  lib/pages/map/map_page.dart
  lib/pages/post/post_page.dart
  lib/pages/profile/edit_profile_page.dart
  lib/pages/register/register_page.dart
  lib/pages/widgets/user_profile_image.dart
  lib/themes/light_theme.dart
Labels: feat

#98 [Board] firebase 연동 및 필터기능 구현
  lib/data/models/board.dart
  lib/data/repositories/board_repository.dart
  lib/data/view_models/board_view_model.dart
  lib/pages/board/board_page.dart
  lib/pages/board/widgets/filter_button.dart
  test/widget_test.dart
Labels: feat

#109 fix: readMe 수정
  README.md
Labels: fix

#114 [Feat]README
  assets/images/exercise_marker.png
  lib/data/view_models/map_view_model.dart
Labels: refactor

#124 [board] 게시판 작성 기능 개발
  lib/data/view_models/board_view_model.dart
  lib/pages/board/create_board_page.dart
  lib/pages/board/create_post_page.dart
  lib/pages/board/widgets/time_selector.dart
  lib/pages/board/widgets/type_button.dart
  lib/pages/home/widgets/home_content_page.dart
Labels: feat
